### ISSUE TITLE
F5 CIS -UI问题记录

### ISSUE THREAD

**Issue by rootwuj** [rootwuj/test-plan#11]
设计测试用例时发现的一些问题记录：

### 优先级较高的问题：
- 问题 5
- 问题 13
- 问题 11

- [x] 1. F5 CIS 英文下菜单标题不一致
![image](https://user-images.githubusercontent.com/42061003/108653274-ff621580-7500-11eb-91f4-ef3647fcb2f6.png)
- [x] 2. F5 CIS 未开启的中文提示信息建议查看监控的翻译修改为：F5 负载均衡服务在当前集群中尚未开启。
![image](https://user-images.githubusercontent.com/42061003/108653445-67186080-7501-11eb-975d-389820886e65.png)
![image](https://user-images.githubusercontent.com/42061003/108668061-5eca2080-7515-11eb-9f3f-beb631c5891f.png)
- [x] 3. 中文，big-ip url 输入框提示信息没有翻译为“例如”
![image](https://user-images.githubusercontent.com/42061003/108663453-90d68500-750b-11eb-94df-20b543c2d1c1.png)
- [x] 4. 选择cluster 的提示信息缺少句号
![image](https://user-images.githubusercontent.com/42061003/108663639-fd518400-750b-11eb-84e6-b23ab75064bc.png)

**Comment by rootwuj** [comment]
- [ ] 5. 4层负载均衡无法编辑，提示："规则" 必须设置
![image](https://user-images.githubusercontent.com/42061003/108677485-b8861700-7524-11eb-9e33-290f45b045f3.png)

**Comment by rootwuj** [comment]
- [ ] peng哥提出的选择nodeport时，集群网络如何显示的问题
![image](https://user-images.githubusercontent.com/42061003/108796241-3ef13600-75c3-11eb-86b4-df5d2bff1a04.png)

**Comment by rootwuj** [comment]
- [ ] 8. F5 Ingress Controllers，菜单名称不一致
![image](https://user-images.githubusercontent.com/42061003/108821557-bd1bff80-75f8-11eb-93d2-9ae865e90404.png)

**Comment by rootwuj** [comment]
- [ ] 8. 建议增加参考文档的链接
![image](https://user-images.githubusercontent.com/42061003/108824333-8c3dc980-75fc-11eb-876a-bf02a6a19f82.png)

**Comment by rootwuj** [comment]
- [ ] 9. 建议修改为“添加 F5 负载均衡“
![image](https://user-images.githubusercontent.com/42061003/108824619-e5a5f880-75fc-11eb-8136-1566d80e5bc2.png)

**Comment by rootwuj** [comment]
- [ ] 10. 每个输入框都建议给出一个默认显示的示例
- F5 负载均衡服务页：需要补充 `BIG-IP Partition` 和 `Flannel Name`
![image](https://user-images.githubusercontent.com/42061003/108824934-4fbe9d80-75fd-11eb-9210-c330bf53a5c4.png)
- F5 负载均衡服务： 7层和4层 的所有表单
![image](https://user-images.githubusercontent.com/42061003/108825744-5ac5fd80-75fe-11eb-9180-e386db3a5c65.png)
- TLS：Termination、Client SSL、Server SSL
![image](https://user-images.githubusercontent.com/42061003/108826028-c60fcf80-75fe-11eb-90e4-32a2e22762ff.png)

**Comment by rootwuj** [comment]
- [ ] 10. F5 CIS 启动页面，展开高级选项，有一条默认的空应答，在未添加应答时不应该显示。
![image](https://user-images.githubusercontent.com/42061003/108933860-d4a1c980-7686-11eb-80b2-11941e00c1fa.png)

**Comment by rootwuj** [comment]
- [ ] 11. 添加TLS页面，有两个标题
![image](https://user-images.githubusercontent.com/42061003/108962897-5eb45700-76b4-11eb-8e00-9a1b5fe03092.png)

**Comment by rootwuj** [comment]
- [ ] 12. 添加F5负载均衡，添加描述功能不生效。编辑页没有修改描述的入口。
![image](https://user-images.githubusercontent.com/42061003/108968305-94107300-76bb-11eb-8d16-0ba72a7ebf50.png)

**Comment by rootwuj** [comment]
- [ ] 13. 7层F5负载均衡 目标后端选择workload，修改的时候如果修改了工作负载或者容器端口，再次进入编辑页面就不会显示工作负载。
![image](https://user-images.githubusercontent.com/42061003/108981652-e48dcd80-76c7-11eb-928f-62bdb8c345d9.png)

**Comment by rootwuj** [comment]
- [ ] 13. 添加4层或7层负载均衡，按顺序填写表单，设置了规则-目标后端后，展开标签/注解。注解中可见f5.cattle.io/targets，并且可以修改。如果修改此注解并保存，在f5 big-ip创建virtual server失败。在创建负载均衡时不要让用户看到这个annotation或者不可编辑。
![image](https://user-images.githubusercontent.com/42061003/109110797-bf09ce00-7772-11eb-9d41-c9ee628175c2.png)

**Comment by DaiYuzeng** [comment]
婧姐，我好像没有上面comment的编辑权限，我先记录在这里。

已经修改：1,2,3,4,5,6,7,9,11,12
暂未修改：8，10-1（有两个10），13（需要航哥帮忙看下）
不准备做修改：10-2

10-2 不修改是因为我看监控页面也是默认有一条。

8 和 10-1 我明天问下航哥一些字段的placeholder设置为什么比较好

**Comment by rootwuj** [comment]
- [ ] 14. 创建7层负载均衡选择TLS Profile，想要修改为http，编辑负载均衡TLS Profile切换为“请选择”，这种情况（从选择证书修改为不选择证书）保存校验无法通过。
![image](https://user-images.githubusercontent.com/42061003/109267400-7c182b00-7844-11eb-9e63-6378e2e8f383.png)
![image](https://user-images.githubusercontent.com/42061003/109267484-99e59000-7844-11eb-8e4f-2a46dc8be600.png)

**Comment by rootwuj** [comment]
- [ ] 15. TLS 的域名为必填项，建议在域名后加一个*
![image](https://user-images.githubusercontent.com/42061003/109271406-70c7fe00-784a-11eb-9ef6-242ef146fd30.png)

**Comment by rootwuj** [comment]
- [ ] 16. TLS 的 termination 支持 "edge", "reencrypt", "passthrough"，是否可以把这一项也做成下拉列表形式？而且这个似乎是必填项
![image](https://user-images.githubusercontent.com/42061003/109271795-f6e44480-784a-11eb-934e-726dd55d598d.png)
![image](https://user-images.githubusercontent.com/42061003/109272055-52aecd80-784b-11eb-856a-4e8c64e597fe.png)
https://clouddocs.f5.com/containers/latest/userguide/crd/tlsprofile.html

**Comment by rootwuj** [comment]
- [ ] 17. TLS Profile 应该按当前选择的ns显示数据，目前可以选择project下所有TLS证书。

![image](https://user-images.githubusercontent.com/42061003/109272995-935b1680-784c-11eb-9316-7a782e4c75c6.png)
![image](https://user-images.githubusercontent.com/42061003/109273032-9e15ab80-784c-11eb-8d8b-b3fcb6c2528f.png)

**Comment by DaiYuzeng** [comment]
目前除了14 和 17，我这其它的都改完了。

14 和 17 是一个问题，前端的表单字段如果是空字符串在提交时被自动转成了null。

**Comment by rootwuj** [comment]
- [ ] 18. 访问路径需要增加校验，必须是绝对路径。现在输入非绝对路径也可以保存。
![image](https://user-images.githubusercontent.com/42061003/109468827-2479f980-7aa8-11eb-9a52-cbab1a0054eb.png)

**Comment by rootwuj** [comment]
- [ ] 19. 访问路径后面括号里的内容需要删除掉。
![image](https://user-images.githubusercontent.com/42061003/109469616-3c05b200-7aa9-11eb-88fc-6daaf646928f.png)

**Comment by rootwuj** [comment]
- [ ] 20. 一个7层负载均衡，添加多条规则，规则的访问路径相同时无法创建virtual server。建议前端增加校验，不允许访问路径相同。
![image](https://user-images.githubusercontent.com/42061003/109471054-2c876880-7aab-11eb-977c-a117a1ccf376.png)
![image](https://user-images.githubusercontent.com/42061003/109470919-ff3aba80-7aaa-11eb-933b-2c2ff5bfdc17.png)

**Comment by rootwuj** [comment]
- [ ] 21. 监控，从启用修改为禁用，修改无效，仍然为启用状态。(禁用到启用是生效的)
![image](https://user-images.githubusercontent.com/42061003/109584057-ddd5df00-7b3b-11eb-95ad-810fca7b7aab.png)

**Comment by rootwuj** [comment]
- [ ] 22. 启用监控：建议为 Interval和timeout  添加单位（可以参考健康检查的UI）
![image](https://user-images.githubusercontent.com/42061003/109603311-a166ab00-7b5c-11eb-8dbd-dd855115c72c.png)

**Comment by rootwuj** [comment]
- 23. 监控的timeout字段为非必填，目前用户不填值时会保存为0。这里需要修改一下，用户没有填写的时候，不能传0，而是不传这个字段。
![image](https://user-images.githubusercontent.com/42061003/109608135-5c467700-7b64-11eb-85f1-61dbc0d58609.png)

**Comment by rootwuj** [comment]
- [ ] 24. 7层负载均衡，单独修改地址或者名称都可以修改成功，但是这两个同时修改就会一直loading

**Comment by DaiYuzeng** [comment]
- [ ]  25. 关闭monitor后，没有将rewrite清除

**Comment by rootwuj** [comment]
- [ ] 25. 存在开启监控的负载均衡，编辑页切换监控为禁用，再切换为启用。UI没有带入原数据。

**Comment by rootwuj** [comment]
目前还存在问题的是：  19，20，21，23

未验证：24，25

**Comment by rootwuj** [comment]
- [ ] 26. TLS 表单顺序修改建议：将Termination放到第一个位置，如果选择的是passthrough，则隐藏其他三项。
![image](https://user-images.githubusercontent.com/42061003/109778466-cd0e9180-7c3f-11eb-92d7-bd9aa900fbd2.png)

修改原因：termination设置为passthrough的时候就不需要设置其他的字段了。因此建议UI优化。
![image](https://user-images.githubusercontent.com/42061003/109778533-e44d7f00-7c3f-11eb-9a4e-bb5619722cd0.png)

**Comment by rootwuj** [comment]
- [ ] 27. 添加TLS，需要切换Termination再选择edge才能正常保存，否则yaml中没有termination。

![image](https://user-images.githubusercontent.com/42061003/109907644-abfc7e00-7cdd-11eb-8838-48afdf28277c.png)

**Comment by rootwuj** [comment]
还需要验证的问题：19,20,23（后端问题，稍后可以验证）,25,26,27

**Comment by rootwuj** [comment]
- [ ] 28. 问题：TLS选择的是secret时，目前Termination选择edge或者reencrypt都只展示 clientssl。secret-reencrypt 同时需要设置clientssl和serverssl。
![image](https://user-images.githubusercontent.com/42061003/109930188-51294d80-7d02-11eb-8f19-2a5eb45e4b7e.png)

![image](https://user-images.githubusercontent.com/42061003/109930173-4c649980-7d02-11eb-8ee4-03ea5b967bfa.png)

整体修改建议：
1. Termination 如果选择的是 passthrough ，隐藏其他三个表单。（已经修改）
2. Termination 如果选择的是 edge，则无论Reference是那个值，只显示 client ssl
3. Termination 如果选择的是 reencrypt，则无论Reference是那个值，clientssl 和 serverssl 都显示，并且此时 serverssl 为必填项需要增加校验和UI的*显示。

**Comment by rootwuj** [comment]
- [ ] 29. 7层负载均衡关联TLS profile，删除关联的TLS证书，然后重新编辑7层规则，保存时仍然带有原tls profile的值，即使修改其他的字段也不会把tlsProfileName 置空。
![image](https://user-images.githubusercontent.com/42061003/109934424-7ff5f280-7d07-11eb-9a6d-97933180e056.png)

**Comment by rootwuj** [comment]
- [ ] 30. service 端口，F5只支持端口号，修改建议：把这个端口下拉列表里的端口名称的选项都去掉，只保留端口号的选项。

![image](https://user-images.githubusercontent.com/42061003/109941141-cf3f2180-7d0d-11eb-8c61-783a0c437069.png)

**Comment by rootwuj** [comment]
上述问题已经全部验证通过。

**Comment by rootwuj** [comment]
- [ ] 31. 修改wap字段，清空时提示错误信息

![image](https://user-images.githubusercontent.com/42061003/110090210-fced9e80-7dd1-11eb-8b7c-2e9a1125293f.png)
 
![image](https://user-images.githubusercontent.com/42061003/110090237-05de7000-7dd2-11eb-86e0-c11219abebd5.png)

**Comment by rootwuj** [comment]
上述问题已经全部验证通过。
